[package]

name = "sandstorm-raw-api-example"
version = "0.0.1"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]
edition = "2018"

[[bin]]

name = "server"
path = "src/main.rs"

[dependencies]
capnp = "0.14"
capnp-rpc = "0.14"
futures = "0.3"
mio-uds = "0.6"
sandstorm = "0.0.15"
tokio = { version = "0.2.6", features = ["net", "rt-util", "uds"]}
tokio-util = { version = "0.3.0", features = ["compat"] }
