[package]

name = "sandstorm-raw-api-example"
version = "0.0.1"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]
edition = "2018"

[[bin]]

name = "server"
path = "src/main.rs"

[dependencies]
capnp = "0.12"
capnp-rpc = "0.12"
futures = "0.3"
mio-uds = "0.6"
sandstorm = "0.0.13"
futures-tokio-compat = { git = "https://github.com/dwrensha/futures-tokio-compat", branch = "tokio-0.2" }
tokio = { version = "0.2.6", features = ["net", "rt-util", "uds"]}

